environment:
  matrix:
    - PYTHON: "C:\\Python27"
      TOXENV: "py27"
    - PYTHON: "C:\\Python27-x64"
      TOXENV: "py27"
    - PYTHON: "C:\\Python36"
      TOXENV: "py36"
    - PYTHON: "C:\\Python36-x64"
      TOXENV: "py36"
    - PYTHON: "C:\\Python37"
      TOXENV: "py37"
    - PYTHON: "C:\\Python37-x64"
      TOXENV: "py37"

cache:
    - '%LOCALAPPDATA%\pip\Cache'

version: '{branch}.{build}'

install:
  - "%PYTHON%\\python.exe -m pip install tox"

build: off

test_script:
  - "%PYTHON%\\Scripts\\tox.exe"
