environment:
  matrix:
    - PYTHON: "C:\\Python35"
      TOXENV: "py35"
    - PYTHON: "C:\\Python27"
      TOXENV: "py27"
    - PYTHON: "C:\\Python27-x64"
      TOXENV: "Py27"
    - PYTHON: "C:\\Python35-x64"
      TOXENV: "Py35"

cache:
    - '%LOCALAPPDATA%\pip\Cache'

version: '{branch}.{build}'

install:
  - "%PYTHON%\\python.exe -m pip install tox"

build: off

test_script:
  - "%PYTHON%\\Scripts\\tox.exe"
